apiVersion: v1
kind: Service
metadata:
  name: ps-web-api-lb
  labels:
    app: ps-web-api-lb
spec:
  type: LoadBalancer
  selector:
    app: ps-web-api
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
      nodePort: 31123



