apiVersion: v1
kind: Service
metadata:
  name: ps-mongodb-svc
  labels:
    app: ps-mongodb-svc
spec:
  selector:
    app: ps-mongodb
  ports:
    - port: 27017
      protocol: TCP
      targetPort: mongodb
      name: mongodb

