spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: ps
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
#      - org.springframework.boot.autoconfigure.mongo.MongoReactiveAutoConfiguration
  main:
    banner-mode: off