apiVersion: v1
kind: ConfigMap
metadata:
  name: ps-webapp-config
data:
  nginx.conf: |
    server {
        listen 80;
        index index.html;
        root /usr/share/nginx/sample/dist;
        location / {
            try_files $uri$args $uri$args/ /index.html;
        }
    }
