apiVersion: v1
kind: Service
metadata:
  name: ps-webapp-lb
  labels:
    app: ps-webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: ps-webapp
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
      nodePort: 30123


